name: CI Workflow

# Запуск при каждом push и pull request
on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2

        
      # Шаг 2: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install
        
      - name: Fix permissions for Jest
        run: chmod +x ./node_modules/.bin/jest  # Установка прав на выполнение для Jest

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: npm test

        
     # Шаг 4: Запуск тестов
      - name: Fix permissions for Doc
        run: chmod +x node_modules/.bin/jsdoc
        
      - name: Documentation
        run: npx jsdoc -c jsdoc.json

